server:
  port: 8080

spring:
  security:
    user:
      name: ais
      password: ais
  boot:
    admin:
      ui:
        title: Microservices Admin Dashboard
      context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
