server:
  port: 8080

spring:
  application:
    name: admin-server
  security:
    user:
      name: ais
      password: ais
  boot:
    admin:
      ui:
        title: Microservices Admin Dashboard
      context-path: /
      discovery:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://ais:ais@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
