server:
  port: 8080

spring:
  application:
    name: admin-server
  security:
    user:
      name: ais
      password: ais
  boot:
    admin:
      ui:
        title: Microservices Admin Dashboard
      discovery:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
